libdl_cache.a:dc_set.o datrie_tail_pool.o dl_cache_stub.o
	ar rs libdl_cache.a dc_set.o datrie_tail_pool.o  dl_cache_stub.o
	cp libdl_cache.a ../lib
.PHONY:clean
clean:
	-rm *.o *.a
CPPFLAGS = -I../include
CFLAGS= -g
